### ISSUE TITLE
Can't find plugin on package control?

### ISSUE THREAD

**Issue by kiddten** [asfaltboy/SublimePythonTestRunner#19]
https://packagecontrol.io/search/SublimeTestPlier

**Comment by kiddten** [comment]
found: https://packagecontrol.io/packages/Test%20Plier :)

**Comment by asfaltboy** [comment]
Thanks @kiddick ! Added link to package control to repo description.

**Comment by asfaltboy** [comment]
By the way, please try it out and comment on any issues or questions you may have. I'd like to make it as user friendly as possible.
